# Generated by Django 4.0.6 on 2022-08-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=64)),
                ('phone_number', models.IntegerField(max_length=64)),
                ('Identity_Verification', models.IntegerField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('api_key', models.CharField(max_length=256)),
                ('sec_key', models.CharField(max_length=256)),
            ],
        ),
    ]
