# Generated by Django 4.0.6 on 2022-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Identity_Verification',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=64),
        ),
    ]
