# Generated by Django 4.0.6 on 2022-08-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinfo_identity_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
